apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo-deployment
spec:
  selector:
    matchLabels:
      app: kube-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
        - name: kube-demo-ctnr
          image: deepaksama26/kube-demo:0.0.4-SNAPSHOT
          ports:
            - containerPort: 80



