apiVersion: v1
kind: Service
metadata:
  name: kube-demo-service
  labels:
    app: kube-demo
spec:
  type: NodePort
  ports: 
    - port: 8080
      nodePort: 30001
      targetPort: 8080
  selector:
    app: kube-demo 
