
@startuml
    skinparam backgroundColor #EEEBDC
    skinparam handwritten true

    skinparam sequence {
        ArrowColor DeepSkyBlue
        ActorBorderColor DeepSkyBlue
        LifeLineBorderColor blue
        LifeLineBackgroundColor #A9DCDF
        ParticipantBorderColor DeepSkyBlue
        ParticipantBackgroundColor DodgerBlue
        ParticipantFontName Impact
        ParticipantFontSize 17
        ParticipantFontColor #A9DCDF
        ActorBackgroundColor aqua
        ActorFontColor DeepSkyBlue
        ActorFontSize 17
        ActorFontName Aapex
    }

    Client -> Remote : Connectin Request with public key identity
    Remote -> Remote : Seach public key store with id
    Remote -> Remote : Generate secret key for client
    Remote -> Client : Secret key encripte with client public key
    Client -> Remote : Acknowlegement encrypted with remote secret key
    Remote -> Remote : Mark client as verified
@enduml
